---
- name: Install postgres
  apt: name={{ item }} state=present
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2
    - libpq-dev

- name: Get postgres version (major.minor)
  shell: psql --version | head -1 | awk '{print $3}' | cut -d '.' -f -2
  register: version

- name: Copy pg_hba.conf
  copy: src=pg_hba.conf dest=/etc/postgresql/{{ version.stdout }}/main/pg_hba.conf

- name: Restart postgres
  service: name=postgresql state=restarted

- name: Add role
  sudo_user: postgres
  postgresql_user: name={{ postgres.username }} password={{ postgres.password }} role_attr_flags=CREATEDB,NOSUPERUSER
