---
# https://github.com/sstephenson/ruby-build/issues/690#issuecomment-68113987
- name: Install deps
  sudo: yes
  apt: pkg={{ item }} state=present
  with_items:
    - libffi-dev
    - zlib1g-dev
    - libssl-dev
    - libpq-dev

- name: Check ruby exists
  shell: rbenv versions | grep {{ ruby.version }}
  register: ruby_exists
  ignore_errors: yes

- name: Install ruby w/ rbenv
  shell: rbenv install {{ ruby.version }}
  when: ruby_exists|failed

- name: Set global ruby
  shell: rbenv global {{ ruby.version }}
  when: ruby_exists|failed

- name: Rehash
  shell: rbenv rehash
  when: ruby_exists|failed

